FROM postgres:latest

# Copy initialization script
COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432

# Default environment variables (can be overridden in docker-compose.yml)
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=mydatabase

CMD ["postgres"]
